apiVersion: v1
kind: Service
metadata:
    name: "azdemoaks-12f9"
    labels:
        app: "azdemoaks-12f9"
spec:
    type: LoadBalancer
    ports:
    - port: 90
      targetPort: 90
      protocol: TCP
      name: http
    selector:
        app: "azdemoaks-12f9"