on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azdemoacrtest.azurecr.io
        username: ${{ secrets.acr_azdemoacrtest_username }}
        password: ${{ secrets.acr_azdemoacrtest_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/test" -f  "tst" -t azdemoacrtest.azurecr.io/azdemoaks:${{ github.sha }}
        docker push azdemoacrtest.azurecr.io/azdemoaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azdemoaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azdemoaks439a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azdemoaks439a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azdemoaks439a
        container-registry-url: azdemoacrtest.azurecr.io
        container-registry-username: ${{ secrets.acr_azdemoacrtest_username }}
        container-registry-password: ${{ secrets.acr_azdemoacrtest_password }}
        secret-name: azdemoaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: azdemoaks439a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azdemoacrtest.azurecr.io/azdemoaks:${{ github.sha }}
        imagepullsecrets: |
          azdemoaksdockerauth